# Generated by Django 4.1.4 on 2023-04-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='client',
        ),
    ]
