# Generated by Django 4.1.4 on 2023-04-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('piano', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(max_length=255)),
            ],
        ),
    ]
