# Generated by Django 4.1.4 on 2023-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telefono',
            field=models.CharField(default='', max_length=12),
        ),
    ]
