# Generated by Django 4.1.4 on 2023-04-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='indirizzo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='piano',
            field=models.CharField(default='', max_length=50),
        ),
    ]
