# Generated by Django 4.1.4 on 2023-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_indirizzo_alter_client_piano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='indirizzo',
            field=models.CharField(max_length=255),
        ),
    ]
